# Generated by Django 4.2.1 on 2023-05-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="contraseña",
            new_name="password",
        ),
    ]
