# Generated by Django 4.2.1 on 2023-05-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0004_rename_contraseña_usuario_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="usuario",
            new_name="username",
        ),
    ]
