# Generated by Django 4.2.1 on 2023-05-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0005_rename_usuario_usuario_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorito",
            old_name="usuario",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="parada",
            old_name="numero",
            new_name="parada",
        ),
        migrations.AlterModelTable(
            name="usuario",
            table="emt_api_usuario",
        ),
    ]
