# Generated by Django 4.2.1 on 2023-05-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0006_rename_usuario_favorito_username_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usuario",
            table=None,
        ),
    ]
