# Generated by Django 4.2.1 on 2023-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0007_alter_usuario_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
    ]
