# Generated by Django 4.2.1 on 2023-05-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emt_api", "0008_usuario_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo", models.DateTimeField(auto_now_add=True)),
                (
                    "parada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emt_api.parada"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emt_api.usuario",
                    ),
                ),
            ],
        ),
    ]
